/**
 * MEAN3
 * Api dla MEAN3
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jarek.frydrych@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface LoginParameters {
    username?: string;
    password?: string;
}
